//! Source map for position mapping between generated Python and original Snakemake source.

use std::collections::HashMap;

#[cfg(feature = "serde")]
use serde::Serialize;

/// A mapping from generated Python positions to original Snakemake positions.
#[derive(Debug, Clone, Default)]
#[cfg_attr(feature = "serde", derive(Serialize))]
pub struct SourceMap {
    /// Individual span mappings: generated range → original range.
    pub mappings: Vec<SourceMapping>,
}

/// A single span mapping.
#[derive(Debug, Clone, Copy)]
#[cfg_attr(feature = "serde", derive(Serialize))]
pub struct SourceMapping {
    /// Byte offset in the generated Python.
    pub generated_start: usize,
    /// Length in bytes in the generated Python.
    pub generated_len: usize,
    /// Byte offset in the original Snakemake source.
    pub original_start: usize,
    /// Length in bytes in the original source.
    pub original_len: usize,
}

impl SourceMap {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a mapping entry.
    pub fn push(&mut self, mapping: SourceMapping) {
        self.mappings.push(mapping);
    }

    /// Convert to a line-based map for backward compatibility with
    /// Snakemake's `linemap` dict.
    ///
    /// Returns `HashMap<generated_line, original_line>` (1-indexed).
    pub fn to_linemap(&self, generated: &str, original: &str) -> HashMap<usize, usize> {
        let gen_line_offsets = line_offsets(generated);
        let orig_line_offsets = line_offsets(original);
        let mut linemap = HashMap::new();

        for mapping in &self.mappings {
            let gen_line = offset_to_line(&gen_line_offsets, mapping.generated_start);
            let orig_line = offset_to_line(&orig_line_offsets, mapping.original_start);
            linemap.entry(gen_line).or_insert(orig_line);
        }

        linemap
    }

    /// Look up the original position for a generated byte offset.
    /// Returns `None` if the offset falls in unmapped (synthetic) text.
    pub fn original_offset(&self, generated_offset: usize) -> Option<usize> {
        for mapping in &self.mappings {
            let gen_end = mapping.generated_start + mapping.generated_len;
            if generated_offset >= mapping.generated_start && generated_offset < gen_end {
                let delta = generated_offset - mapping.generated_start;
                if delta < mapping.original_len {
                    return Some(mapping.original_start + delta);
                }
            }
        }
        None
    }

    /// Look up the generated position for an original byte offset.
    /// Returns `None` if the original offset isn't mapped.
    pub fn generated_offset(&self, original_offset: usize) -> Option<usize> {
        for mapping in &self.mappings {
            let orig_end = mapping.original_start + mapping.original_len;
            if original_offset >= mapping.original_start && original_offset < orig_end {
                let delta = original_offset - mapping.original_start;
                if delta < mapping.generated_len {
                    return Some(mapping.generated_start + delta);
                }
            }
        }
        None
    }
}

/// Compute byte offsets of line starts.
fn line_offsets(text: &str) -> Vec<usize> {
    let mut offsets = vec![0];
    for (i, b) in text.bytes().enumerate() {
        if b == b'\n' {
            offsets.push(i + 1);
        }
    }
    offsets
}

/// Convert a byte offset to a 1-indexed line number.
fn offset_to_line(line_offsets: &[usize], offset: usize) -> usize {
    match line_offsets.binary_search(&offset) {
        Ok(line) => line + 1,
        Err(line) => line, // line is the index of the next larger offset
    }
}
